-- Generated by Oracle SQL Developer Data Modeler 4.2.0.932
--   at:        2018-01-18 03:31:20 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE apteka CASCADE CONSTRAINTS;

DROP TABLE dzien CASCADE CONSTRAINTS;

DROP TABLE farmaceuta CASCADE CONSTRAINTS;

DROP TABLE kasa CASCADE CONSTRAINTS;

DROP TABLE kierownik CASCADE CONSTRAINTS;

DROP TABLE klient CASCADE CONSTRAINTS;

DROP TABLE magazyn CASCADE CONSTRAINTS;

DROP TABLE produkty CASCADE CONSTRAINTS;

DROP TABLE rachunki CASCADE CONSTRAINTS;

DROP TABLE recepta CASCADE CONSTRAINTS;

DROP TABLE uzytkownik CASCADE CONSTRAINTS;

DROP TABLE zamowienie CASCADE CONSTRAINTS;

CREATE TABLE apteka (
    id_apteka              NUMBER(6) NOT NULL,
    nazwa                  VARCHAR2(25) NOT NULL,
    adres                  VARCHAR2(25) NOT NULL,
    telefon                NUMBER(9) NOT NULL,
    uzytkownik_id          NUMBER(9) NOT NULL,
    "Magazyn_id magazyn"   NUMBER(9) NOT NULL,
    "Kasa_id kasa"         NUMBER(9) NOT NULL
)
    LOGGING;

ALTER TABLE apteka ADD CONSTRAINT apteka_pk PRIMARY KEY ( id_apteka );

CREATE TABLE dzien (
    "id_dzien"                  NUMBER(9) NOT NULL,
    pieniadze                   NUMBER(9) NOT NULL,
    iloscsprzedanychproduktow   NUMBER(9) NOT NULL,
    data                        DATE
)
    LOGGING;

ALTER TABLE dzien ADD CONSTRAINT dzien_pk PRIMARY KEY ( "id_dzien" );

CREATE TABLE farmaceuta (
    id_farmaceuta            NUMBER(9) NOT NULL,
    wynagrodzenie              NUMBER(9) NOT NULL,
    konto_bankowe              NUMBER(26),
    uzytkownik_id_uzytkownik   NUMBER(9) NOT NULL
)
    LOGGING;

ALTER TABLE farmaceuta ADD CONSTRAINT farmaceuta_pk PRIMARY KEY ( id_farmaceuta );

CREATE TABLE kasa (
    "id_kasa"                NUMBER(9) NOT NULL,
    pieniadze                NUMBER(9) NOT NULL,
    dzien                    DATE NOT NULL,
    "Rachunki_id rachunki"   NUMBER(9) NOT NULL,
    "Dzien_id dzien"         NUMBER(9) NOT NULL
)
    LOGGING;

ALTER TABLE kasa ADD CONSTRAINT kasa_pk PRIMARY KEY ( "id_kasa" );

CREATE TABLE kierownik (
    id_kierownik             NUMBER(9) NOT NULL,
    uzytkownik_id_uzytkownik   NUMBER(9) NOT NULL
)
    LOGGING;

ALTER TABLE kierownik ADD CONSTRAINT kierownik_pk PRIMARY KEY ( id_kierownik );

CREATE TABLE klient (
    id_klient                  NUMBER(9) NOT NULL,
    uzytkownik_id_uzytkownik   NUMBER(9) NOT NULL
)
    LOGGING;

ALTER TABLE klient ADD CONSTRAINT klient_pk PRIMARY KEY ( id_klient );

CREATE TABLE magazyn (
    "id_magazyn"              NUMBER(9) NOT NULL,
    ilosc_wolnych_miejsc      NUMBER(6) NOT NULL,
    zamowienie_idzamowienia   NUMBER(9) NOT NULL,
    "Produkty_id produkty"    NUMBER(9) NOT NULL
)
    LOGGING;

ALTER TABLE magazyn ADD CONSTRAINT magazyn_pk PRIMARY KEY ( "id_magazyn" );

CREATE TABLE produkty (
    "id_produkty"   NUMBER(9) NOT NULL,
    nazwa           VARCHAR2(25) NOT NULL,
    dawka           VARCHAR2(25) NOT NULL,
    typ             VARCHAR2(25) NOT NULL,
    ilosc           NUMBER(6)
)
    LOGGING;

ALTER TABLE produkty ADD CONSTRAINT produkty_pk PRIMARY KEY ( "id_produkty" );

CREATE TABLE rachunki (
    "id_rachunki"   NUMBER(9) NOT NULL,
    seria           NUMBER(9) NOT NULL
)
    LOGGING;

ALTER TABLE rachunki ADD CONSTRAINT rachunki_pk PRIMARY KEY ( "id_rachunki" );

CREATE TABLE recepta (
    id_recepta            NUMBER(9) NOT NULL,
    kodrecepty            NUMBER(9),
    informacjaodlekarza   VARCHAR2(30)
)
    LOGGING;

ALTER TABLE recepta ADD CONSTRAINT recepta_pk PRIMARY KEY ( id_recepta );

CREATE TABLE uzytkownik (
    id_uzytkownik   NUMBER(9) NOT NULL,
    nazwau          VARCHAR2(25) NOT NULL,
    haslo           VARCHAR2(25) NOT NULL,
    imie            VARCHAR2(25) NOT NULL,
    wiek            NUMBER(3) NOT NULL,
    nazwisko        VARCHAR2(25) NOT NULL,
    typ           VARCHAR2(15) NOT NULL
)
    LOGGING;

ALTER TABLE uzytkownik ADD CONSTRAINT uzytkownik_pk PRIMARY KEY ( id_uzytkownik );

CREATE TABLE zamowienie (
    id_zamowienia            NUMBER(9) NOT NULL,
    "Produkty_id produkty"   NUMBER(9) NOT NULL
)
    LOGGING;

ALTER TABLE zamowienie ADD CONSTRAINT zamowienie_pk PRIMARY KEY ( id_zamowienia );

ALTER TABLE apteka ADD CONSTRAINT apteka_kasa_fk FOREIGN KEY ( "Kasa_id kasa" )
    REFERENCES kasa ( "id_kasa" )
NOT DEFERRABLE;

ALTER TABLE apteka ADD CONSTRAINT apteka_magazyn_fk FOREIGN KEY ( "Magazyn_id magazyn" )
    REFERENCES magazyn ( "id_magazyn" )
NOT DEFERRABLE;

ALTER TABLE apteka ADD CONSTRAINT apteka_uzytkownik_fk FOREIGN KEY ( uzytkownik_id )
    REFERENCES uzytkownik ( id_uzytkownik )
NOT DEFERRABLE;

ALTER TABLE farmaceuta ADD CONSTRAINT farmaceuta_uzytkownik_fk FOREIGN KEY ( uzytkownik_id_uzytkownik )
    REFERENCES uzytkownik ( id_uzytkownik )
NOT DEFERRABLE;

ALTER TABLE kasa ADD CONSTRAINT kasa_dzien_fk FOREIGN KEY ( "Dzien_id dzien" )
    REFERENCES dzien ( "id_dzien" )
NOT DEFERRABLE;

ALTER TABLE kasa ADD CONSTRAINT kasa_rachunki_fk FOREIGN KEY ( "Rachunki_id rachunki" )
    REFERENCES rachunki ( "id_rachunki" )
NOT DEFERRABLE;

ALTER TABLE kierownik ADD CONSTRAINT kierownik_uzytkownik_fk FOREIGN KEY ( uzytkownik_id_uzytkownik )
    REFERENCES uzytkownik ( id_uzytkownik )
NOT DEFERRABLE;

ALTER TABLE klient ADD CONSTRAINT klient_uzytkownik_fk FOREIGN KEY ( uzytkownik_id_uzytkownik )
    REFERENCES uzytkownik ( id_uzytkownik )
NOT DEFERRABLE;

ALTER TABLE magazyn ADD CONSTRAINT magazyn_produkty_fk FOREIGN KEY ( "Produkty_id produkty" )
    REFERENCES produkty ( "id_produkty" )
NOT DEFERRABLE;

ALTER TABLE magazyn ADD CONSTRAINT magazyn_zamowienie_fk FOREIGN KEY ( zamowienie_idzamowienia )
    REFERENCES zamowienie ( id_zamowienia )
NOT DEFERRABLE;

ALTER TABLE zamowienie ADD CONSTRAINT zamowienie_produkty_fk FOREIGN KEY ( "Produkty_id produkty" )
    REFERENCES produkty ( "id_produkty" )
NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
